app:
  env: dev
  port: 8080
  host: localhost
  timeout: 5s
  idle_timeout: 60s

db:
  name: auth-db
  host: localhost
  port: 5432
  user: devvdark0-auth-user-db!
  max_idle_conn: 10
  max_open_conn: 10
  max_conn_time_sec: 180s
  sslmode: disable